#!/bin/sh

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

LOG_DIR="/var/log/digitemp"
OUTPUT=`/usr/local/bin/digitemp_DS9097U -q -c /etc/digitemp.conf -o 2 -a |cut -f2-`
SENSOR_ID=0

for SENSOR in $OUTPUT
do
    echo `date +%Y%m%d%H%M%S` $SENSOR >> $LOG_DIR/full_temp$SENSOR_ID.dat
    echo $SENSOR > $LOG_DIR/current_temp$SENSOR_ID.dat
    SENSOR_ID=$((SENSOR_ID+1))
done
